name: Publish package to github packages

on:
  push:
    branches:
      - "**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Pack
      run: dotnet pack --no-build -c Release -o ./package

    - name: Get csproj version
      run: PKG_VERSION=$(sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p' ./src/Calculator/Calculator.csproj); echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV

    - name: Set RC version of package if branch is not main
      if: github.ref != 'refs/heads/main'
      run: PKG_FINAL_VERSION=$PKG_VERSION-rc$(date +"%Y%m%d.%H%M%S"); echo "PKG_FINAL_VERSION=$PKG_FINAL_VERSION" >> $GITHUB_ENV

    - name: Set final version of package if branch is main
      if: github.ref == 'refs/heads/main'
      run: PKG_FINAL_VERSION=$PKG_VERSION; echo "PKG_FINAL_VERSION=$PKG_FINAL_VERSION" >> $GITHUB_ENV

    - name: Rename file to final version
      run: mv ./package/Calculator.$PKG_VERSION.nupkg ./package/Calculator.$PKG_FINAL_VERSION.nupkg

    - name: Publish
      run: dotnet nuget push "./package/Calculator.$PKG_FINAL_VERSION.nupkg" --api-key ${{ secrets.GITHUBPACKAGES }} --source https://nuget.pkg.github.com/fosouzadev/index.json