name: Publish package to github packages

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Get csproj version
      run: PKG_VERSION=$(sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p' ./src/Calculator/Calculator.csproj); echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV

    - name: Set new csproj version if branch is not main
      if: github.ref != 'refs/heads/main'
      run:  PKG_VERSION=$PKG_VERSION-rc$(date +"%Y%m%d%H%M%S"); sed -i "s/<Version>.*<\/Version>/<Version>${PKG_VERSION}<\/Version>/g" ./src/Calculator/Calculator.csproj; echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV

    - name: Pack
      run: dotnet pack --no-build -c Release -o ./package

    - name: Publish
      run: dotnet nuget push ./package/Calculator.$PKG_VERSION.nupkg --api-key ${{ secrets.GITHUBPACKAGES }} --source https://nuget.pkg.github.com/fosouzadev/index.json